# Generated by Django 6.0.4 on 2026-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Skin Sensation Spa', max_length=255)),
                ('phone_number', models.CharField(help_text='Display format, e.g. +260 973 407 110', max_length=20)),
                ('whatsapp_number', models.CharField(help_text='Digits only for wa.me links, e.g. 260973407110', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('google_maps_embed_url', models.TextField(blank=True, help_text='Full iframe src URL from Google Maps → Share → Embed')),
                ('opening_hours', models.JSONField(blank=True, default=dict)),
                ('whatsapp_prefill_message', models.TextField(blank=True, default='Hello Skin Sensation Spa, I would like to inquire about your services.')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business information',
                'verbose_name_plural': 'Business information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
