# Generated by Django 6.0.4 on 2026-05-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_seed_business_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(choices=[('general', 'General enquiry'), ('booking', 'Booking help'), ('group', 'Group / event booking'), ('services', 'Services question'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=50),
        ),
    ]
