# Generated by Django 6.0.4 on 2026-05-27 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_alter_contactmessage_phone_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, help_text="Pill text shown on the card, e.g. 'Service Notice' or 'Promotion'.", max_length=50)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='announcements/')),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateField(blank=True, help_text='First date to show this card. Leave blank to show immediately.', null=True)),
                ('ends_at', models.DateField(blank=True, help_text='Last date to show this card. Leave blank to show indefinitely.', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
