# Generated by Django 6.0.4 on 2026-05-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('interior', 'Spa Interior'), ('facials', 'Facials'), ('massage', 'Massage'), ('body-nails', 'Body & Nails'), ('team', 'Team & Atmosphere')], max_length=20)),
                ('caption', models.CharField(max_length=255)),
                ('alt_text', models.CharField(max_length=255)),
                ('layout', models.CharField(choices=[('default', 'Default'), ('wide', 'Wide'), ('tall', 'Tall')], default='default', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'category', 'sort_order'], name='gallery_gal_is_acti_6fcaee_idx')],
            },
        ),
    ]
