# Generated by Django 6.0.4 on 2026-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'service categories'},
        ),
        migrations.AddField(
            model_name='service',
            name='price_from',
            field=models.BooleanField(default=False, help_text='Show "From" before the price (e.g. variable or tiered pricing).'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_label',
            field=models.CharField(blank=True, help_text='Optional override, e.g. K500–K1,000', max_length=64),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
