# Generated by Django 6.0.4 on 2026-05-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_legacy_catalog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='treatment',
            new_name='services_tr_is_acti_4c722b_idx',
            old_name='services_tr_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='treatment',
            new_name='services_tr_service_5e5f8b_idx',
            old_name='services_tr_service_idx',
        ),
    ]
