# Generated by Django 6.0.4 on 2026-05-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_services_tr_is_acti_idx_services_tr_is_acti_4c722b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['name'], name='services_tr_name_503d7c_idx'),
        ),
    ]
