# Generated by Django 6.0.4 on 2026-05-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_verified', 'Payment verified'), ('payment_rejected', 'Payment rejected'), ('payment_recorded', 'Payment recorded'), ('appointment_status', 'Appointment status changed'), ('appointment_rescheduled', 'Appointment rescheduled'), ('service_toggled', 'Service active toggled'), ('treatment_toggled', 'Treatment active toggled'), ('review_approved', 'Review approved'), ('review_rejected', 'Review rejected'), ('review_featured', 'Review featured'), ('review_deleted', 'Review deleted')], max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='dashboard_s_created_5960b5_idx'), models.Index(fields=['action'], name='dashboard_s_action_4512d0_idx')],
            },
        ),
    ]
