# Generated by Django 6.0.4 on 2026-05-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_staffactivitylog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactivitylog',
            name='action',
            field=models.CharField(choices=[('payment_verified', 'Payment verified'), ('payment_rejected', 'Payment rejected'), ('payment_recorded', 'Payment recorded'), ('appointment_status', 'Appointment status changed'), ('appointment_rescheduled', 'Appointment rescheduled'), ('service_toggled', 'Service active toggled'), ('treatment_toggled', 'Treatment active toggled'), ('review_approved', 'Review approved'), ('review_rejected', 'Review rejected'), ('review_featured', 'Review featured'), ('review_deleted', 'Review deleted'), ('customer_note_added', 'Customer note added'), ('contact_message_status', 'Contact message status changed'), ('contact_message_deleted', 'Contact message deleted'), ('gallery_created', 'Gallery image created'), ('gallery_updated', 'Gallery image updated'), ('gallery_deleted', 'Gallery image deleted')], max_length=40),
        ),
    ]
