# Generated by Django 6.0.4 on 2026-05-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='customers/avatars/'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
