# Generated by Django 6.0.4 on 2026-05-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationlog',
            name='notifications_log_appt_template_uniq',
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'SENT')), fields=('appointment', 'template_key'), name='notifications_log_appt_template_sent_uniq'),
        ),
    ]
