# Generated by Django 6.0.4 on 2026-05-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_log_appt_template_sent_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10),
        ),
    ]
